'use client'
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 spaceship.glb 
Author: Rogin (https://sketchfab.com/Rogin)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spaceship-cb1-822e68ddbadd49e7b4c6c7b38081f1a2
Title: Spaceship-cb1
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'

export function Spaceship(props) {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF('/spaceship.glb')
    const { actions } = useAnimations(animations, group)

    useEffect(() => {
        for (const actionName in actions) {
            actions[actionName].play()
        }
    }, [actions])

    // const helix = useRef()
    // const HELIX_SPEED = 6
    // useFrame((_state, delta) => {
    //     helix.current.rotation.x += delta * HELIX_SPEED
    // })
    return (
        <>
            <directionalLight position={[0, 3, 1]} intensity={0.1} />
            <group ref={group} {...props} dispose={null}>
                <group name="Sketchfab_Scene">
                    <group
                        name="Sketchfab_model"
                        rotation={[-Math.PI / 2, 0, 0]}
                    >
                        <group
                            name="gemi_sketchfabfbx"
                            rotation={[Math.PI / 2, 0, 0]}
                            scale={0.003}
                        >
                            <group name="Object_2">
                                <group name="RootNode">
                                    <group
                                        name="Cube"
                                        position={[-2460.281, 286.608, 0]}
                                        rotation={[-Math.PI / 2, 0, 0]}
                                        scale={100}
                                    >
                                        <mesh
                                            name="Cube_Material_0"
                                            geometry={
                                                nodes.Cube_Material_0.geometry
                                            }
                                        >
                                            <meshStandardMaterial color="white" />
                                        </mesh>
                                        <mesh
                                            name="Cube_Material_0_1"
                                            geometry={
                                                nodes.Cube_Material_0_1.geometry
                                            }
                                        >
                                            <meshStandardMaterial color="white" />
                                        </mesh>
                                    </group>
                                    <group
                                        name="Armature002"
                                        position={[-2060.829, 0, 0]}
                                        rotation={[-Math.PI / 2, 0, 0]}
                                        scale={100}
                                    >
                                        <group name="Object_8">
                                            <primitive
                                                object={nodes._rootJoint}
                                            />
                                        </group>
                                    </group>
                                    <group
                                        name="HOPS_Light_Empty"
                                        position={[-2460.281, 286.608, 0]}
                                        rotation={[-Math.PI / 2, 0, 2.898]}
                                        scale={100}
                                    />
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </>
    )
}

useGLTF.preload('/spaceship.glb')
