/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 star.glb 
Author: Aricode (https://sketchfab.com/Aricode)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/star-d0fc8d9154554ca4a90bd86a01a7d9d7
Title: Star
*/

import React, { useRef } from 'react'
import { Float, useGLTF } from '@react-three/drei'
import { fadeOnBeforeCompile } from '../../utils/fadeMaterial'
import { useFrame } from '@react-three/fiber'

export function Star({ sceneOpacity, ...props }) {
    const { nodes, materials } = useGLTF('/star.glb')
    const materialRef = useRef()

    useFrame(() => {
        materialRef.current.opacity = sceneOpacity.current
    })
    return (
        <>
            <Float floatIntensity={0.1} speed={0.1} rotationIntensity={0.3}>
                <group {...props} dispose={null}>
                    <mesh
                        geometry={nodes.Star_0.geometry}
                        rotation={[-Math.PI / 2, 0, 0]}
                    >
                        <meshStandardMaterial
                            ref={materialRef}
                            onBeforeCompile={fadeOnBeforeCompile}
                            {...materials['Material.001']}
                            envMapIntensity={2}
                            transparent
                        />
                    </mesh>
                </group>
            </Float>
        </>
    )
}

useGLTF.preload('/star.glb')
