/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 strunned_stars.glb 
Author: FunkyDealer (https://sketchfab.com/FunkyDealer)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/strunned-stars-7ca25a3c7ec243c4b790dbdd826f5277
Title: Strunned Stars
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function StrunnedStars(props) {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF('/strunned_stars.glb')
    const { actions } = useAnimations(animations, group)
    useEffect(() => {
        for (const actionName in actions) {
            actions[actionName].play()
        }
    }, [actions])
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Sketchfab_Scene">
                <group
                    name="Sketchfab_model"
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={0.088}
                >
                    <group
                        name="8b3b2a2ec3d642feb5084bc49b748085fbx"
                        rotation={[Math.PI / 2, 0, 0]}
                    >
                        <group name="Object_2">
                            <group name="RootNode">
                                <group name="Controllers">
                                    <group
                                        name="MainRotator"
                                        position={[0, 6.151, 0]}
                                        rotation={[0, 1.248, 0]}
                                        scale={18.902}
                                    >
                                        <group
                                            name="Star1"
                                            position={[0.56, 0.033, -0.289]}
                                            rotation={[1.312, 0.605, -0.093]}
                                            scale={0.053}
                                        />
                                        <group
                                            name="Star2"
                                            position={[-0.05, 0.036, -0.658]}
                                            rotation={[-0.33, 0.554, -1.012]}
                                            scale={0.053}
                                        />
                                        <group
                                            name="star3"
                                            position={[-0.601, -0.039, -0.334]}
                                            rotation={[-0.905, 0.237, -0.514]}
                                            scale={0.053}
                                        />
                                        <group
                                            name="star4"
                                            position={[-0.548, 0.046, 0.337]}
                                            rotation={[-0.281, 0.682, 1.512]}
                                            scale={0.053}
                                        />
                                        <group
                                            name="star5"
                                            position={[0, 0.01, 0.659]}
                                            rotation={[0.084, 0.337, 1.106]}
                                            scale={0.053}
                                        />
                                        <group
                                            name="star6"
                                            position={[0.538, 0.025, 0.366]}
                                            rotation={[0.159, -0.191, 0.701]}
                                            scale={0.053}
                                        />
                                    </group>
                                </group>
                                <group name="Polygons_Bones_DoNotTouch">
                                    <group name="Object_13">
                                        <primitive object={nodes._rootJoint} />
                                    </group>
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/strunned_stars.glb')
